source/accounts/urls.py
from django.urls import path, include, re_path
from accounts.views import RegisterView, UserDetailView, UsersListView, UserChangeView, UserPasswordChangeView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    # re_path(r'^login?/$', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('users/', UsersListView.as_view(), name='users'),
    path('change/', UserChangeView.as_view(), name='change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

source/bishop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from webapp.views import ProductList, ProductDetail, ProductCreate, ProductUpdate, ProductDelete, AddItemToCart, \
    CartList, CartDelete, OrderCreate, CartDeleteOne

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_avatar', verbose_name='Аватар')
    github = models.URLField(max_length=50, null=True, blank=True, verbose_name='Ссылка на github')
    bio = models.TextField(null=True, blank=True, verbose_name='О себе')

    def __str__(self):
        return f"{self.user.username} 's Profile"

    class Meta:
        db_table = 'profile'
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
        permissions = [
            ('can_view_all_users', 'Can view all users')
        ]

source/accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=100, required=False)

    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']

class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}

class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'birth_date']

class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
from django.contrib.auth import login
from django.urls import reverse
from django.contrib.auth.views import PasswordChangeView

from .forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.list import MultipleObjectMixin
from accounts.models import Profile

# Create your views here.

class RegisterView(CreateView):
    model = get_user_model()
    form_class = MyUserCreationForm
    template_name = 'user_create.html'

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        next_url = self.request.POST.get('next')
        if next_url:
            return next_url
        return reverse('webapp:index')

class UserDetailView(LoginRequiredMixin, DetailView, MultipleObjectMixin):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        products = self.get_object().products.all()
        return super().get_context_data(object_list=products, **kwargs)

class UsersListView(PermissionRequiredMixin, ListView):
    model = get_user_model()
    template_name = 'users.html'
    context_object_name = 'users_obj'
    paginate_by = 5

    def has_permission(self):
        return self.request.user.has_perm('accounts.can_view_all_users') and self.request.user in User.objects.all() or self.request.user.is_superuser

class UserChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'
    form_profile_class = ProfileChangeForm

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'profile_form' not in kwargs:
            context['profile_form'] = self.form_profile_class(instance=self.get_object().profile)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.form_profile_class(instance=self.get_object().profile, data=request.POST, files=request.FILES)
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        return self.render_to_response(self.get_context_data(form=form, profile_form=profile_form))

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.get_object().pk})

class UserPasswordChangeView(PasswordChangeView):
    template_name = 'user_password_change.html'
    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.request.user.pk})

source/accounts/templates/login.html
{% extends 'base.html' %}

{%  block content %}
    <title>Вход</title>

</head>

<body>

<div class="container">
    <h1>Вход</h1>
    <form action="" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="text-danger">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" name="password" id="password">
        </div>
        <button type="submit">Войти</button>
    </form>
{% endblock %}

source/accounts/templates/user_change.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit user</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% include 'partial/form.html' with fields_only=True %}
    {% include 'partial/form.html' with form=profile_form button_text='Edit' %}
</form>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}

{% block content %}
<h1>Create User</h1>
<form action="" method="post">
    {% include 'partial/form.html' with button_text='Register' %}
</form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:project_add' %}">Create Project ( + )</a>
    </li>
    {% if user_obj.pk == request.user.pk %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change' %}">Edit user</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:password_change' %}">Change password</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
    <div class="card mb-3">
  <div class="row g-0">
      {% if user_obj.profile.avatar %}
        <div class="col-md-4">
          <img src="{{ user_obj.profile.avatar.url }}" class="img-fluid rounded-start">
        </div>
      {% endif %}
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Имя пользователя: {{ user_obj.username }}</h5>
            <p class="card-text">Имя: {{ user_obj.first_name }}</p>
            <p class="card-text">Фамилия: {{ user_obj.last_name }}</p>
            <p class="card-text">Дата рождения: {{ user_obj.profile.birth_date|date:'d.m.Y' }}</p>
            <p class="card-text">Почта: {{ user_obj.email }}</p>
            <p class="card-text">Git: {{ user_obj.github }}</p>
            <p class="card-text">О себе: {{ user_obj.bio }}</p>
          </div>
        </div>
  </div>
</div>
{% include 'partial/project_list_partial.html' with products=object_list %}
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block content %}
<h1>Change Password</h1>
<form action="" method="post">
    {% include 'partial/form.html' with button_text='Change password' %}
</form>
{% endblock %}

source/accounts/templates/users.html
{% extends 'base.html' %}
{% block nav %}
{% endblock %}
{% block content %}
<h1>All users</h1>
<div class="row">
    {% for user_obj in users_obj %}
        <div class="col col-lg-4 my-2">
            <div class="card">
                <h5 class="card-header"> Name: <a href="{% url 'accounts:detail' user_obj.pk %}">{{ user_obj }}</a></h5>
{#                <p class="card-text text-secondary">Пользователь: {{ project.users }}</p>#}
{#                <div class="card-body">#}
{#                    <h5 class="card-title">Дата начала:{{ user_obj.start_at }} </h5>#}
{#                    <p class="card-text">Дата окончания: {{ project.end_at|default:"-" }} </p>#}
{#                </div>#}
            </div>
        </div>
    {% endfor %}
</div>
{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}
{% endblock %}