source/bishop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from webapp.views import ProductList, ProductDetail, ProductCreate, ProductUpdate, ProductDelete, AddItemToCart, \
    CartList, CartDelete, OrderCreate, CartDeleteOne

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.contrib import admin
from django.urls import path
from webapp.views import ProductList, ProductDetail, ProductCreate, ProductUpdate, ProductDelete, AddItemToCart, \
    CartList, CartDelete, OrderCreate, CartDeleteOne

app_name = 'webapp'

urlpatterns = [
    path('', ProductList.as_view(), name='index'),
    path('product/<int:pk>/view/', ProductDetail.as_view(), name='product_view'),
    path('product/<int:pk>/add_to_cart/', AddItemToCart.as_view(), name='add_to_cart'),
    path('product/<int:pk>/update/', ProductUpdate.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDelete.as_view(), name='product_delete'),
    path('product/add/', ProductCreate.as_view(), name='product_add'),
    path('cart/', CartList.as_view(), name='cart_index'),
    path('order/', OrderCreate.as_view(), name='order_create'),
    path('cart/<int:pk>/delete/', CartDelete.as_view(), name='cart_delete'),
    path('cart/<int:pk>/delete_one/', CartDeleteOne.as_view(), name='cart_delete_one'),
]

source/webapp/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth import get_user_model

CATEGORIES_CHOICES = [("other", "Разное"), ("electronics", "Электроника"), ("books", "Книги"),
                      ("stationery", "Канцтовары")]
ORDER_STATUSES = [("new", 'Новое'), ("completed", "Завершенный")]


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Наименование товара')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание товара')
    category = models.CharField(max_length=50, choices=CATEGORIES_CHOICES, default=CATEGORIES_CHOICES[0][0],
                                verbose_name="Категория")
    balance = models.PositiveIntegerField(verbose_name='Остаток')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Стоимость",
                                validators=(MinValueValidator(0),))

    def __str__(self):
        return f'{self.id}. {self.name} - {self.balance}'

    class Meta:
        ordering = ['-id']


# class Cart(models.Model):
#     product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE, related_name='cart', verbose_name='Товар')
#     qty = models.PositiveIntegerField(default=0, verbose_name='Количество')
#
#     def __str__(self):
#         return f'{self.product.name} - {self.qty}'
#
#     def get_product_total(self):
#         return self.qty * self.product.price
#
#     @classmethod
#     def get_total(cls):
#         total = 0
#         for cart in cls.objects.all():
#             total += cart.get_product_total()
#         return total


class OrderProduct(models.Model):
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE, verbose_name='Товар')
    order = models.ForeignKey('webapp.Order', on_delete=models.CASCADE, related_name="products", verbose_name='Заказ')
    qty = models.PositiveIntegerField(verbose_name='Количество')

    def get_product_total(self):
        return self.qty * self.product.price

    # class Meta:
    #     fields = ('product', 'order', 'qty')



class Order(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Имя пользователя')
    phone = models.CharField(max_length=100, null=False, blank=False, verbose_name='Телефон')
    address = models.CharField(max_length=100, null=False, blank=False, verbose_name='Адрес')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')
    # products = models.ManyToManyField('webapp.Product', related_name='order', through='webapp.OrderProduct',
    #                                   through_fields=['order', 'product'], verbose_name='Товары')
    users = models.ForeignKey(get_user_model(), related_name='orders', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='Пользователь')
    session = models.CharField(max_length=100, null=True, blank=True, verbose_name='Сессия')
    status = models.CharField(max_length=100, null=False, blank=False, choices=ORDER_STATUSES, default=ORDER_STATUSES[0][0], verbose_name='Status')

    @classmethod
    def get_total(self):
        total = 0
        for item in self.products.all():
            total += item.get_product_total()
        return total

source/webapp/forms.py
from django import forms
from django.forms import widgets

from webapp.models import Product, Order


class SearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label="Найти")


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'category', 'balance', 'price']


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'phone', 'address']

source/webapp/views.py
from django.shortcuts import render

# Create your views here.

source/webapp/views/base_views.py
from django.db.models import Q
from django.utils.http import urlencode
from django.views.generic import ListView


class SearchView(ListView):
    search_form_class = None
    search_form_field = 'search'
    query_name = 'query'
    search_fields = [] # ['title__icontains', 'author__icontains']


    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        if self.search_form_class:
            return self.search_form_class(self.request.GET)

    def get_search_value(self):
        if self.form:
            if self.form.is_valid():
                return self.form.cleaned_data[self.search_form_field]

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(self.get_query()) # filter(Q()) == all()
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        if self.form:
            context['form'] = self.form
            if self.search_value:
                context[self.query_name] = urlencode({self.search_form_field: self.search_value})
                context[self.search_form_field] = self.search_value
        return context

    def get_query(self):
        query = Q()
        for field in self.search_fields:
            kwargs = {field: self.search_value} # {'title__icontains': 'task 1' }
            query = query | Q(**kwargs) # Q(title__icontains='task 1')
        return query

source/webapp/views/cart_views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import View, ListView, DeleteView, CreateView
from django.shortcuts import redirect, get_object_or_404

from webapp.models import Product, Order, OrderProduct
from webapp.forms import OrderForm


class AddItemToCart(View):
    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=kwargs.get('pk'))
        qty = int(request.POST.get('qty'))

        cart, _ = Order.objects.get_or_create(products=product)
        # cart = Order.objects.get_or_create(status='new', session=request.session._session_key)
        # cart_item, _ = OrderProduct.objects.get_or_create(order=cart.pk, product=product.pk)

        if product.balance >= cart.product + qty:
            cart.qty += qty
            cart.save()

        return redirect(self.get_redirect_url())

    def get_redirect_url(self):
        next = self.request.GET.get('next')
        if next:
            return next
        return reverse('webapp:index')


class CartList(ListView):
    model = Order
    template_name = 'cart/index.html'
    context_object_name = "carts"

    def get_context_data(self, *, object_list=None, **kwargs):
        print(self.request.session['key'])
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['total'] = Order.get_total()
        context['form'] = OrderForm
        return context


class CartDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('webapp:cart_index')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)


class CartDeleteOne(DeleteView):
    model = Order
    success_url = reverse_lazy('webapp:cart_index')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.qty -= 1
        if self.object.qty < 1:
            self.object.delete()
        else:
            self.object.save()
        return redirect(success_url)


class OrderCreate(CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('webapp:index')

    def form_valid(self, form):
        order = form.save()

        for item in Order.objects.all():
            OrderProduct.objects.create(product=item.product, qty=item.qty, order=order)
            item.product.balance -= item.qty
            item.product.save()
            item.delete()

        return redirect(self.success_url)

source/webapp/views/product_views.py
from webapp.forms import SearchForm, ProductForm
from webapp.models import Product
from webapp.views.base_views import SearchView
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect


class ProductList(SearchView):
    model = Product
    template_name = 'product/index.html'
    context_object_name = 'products'
    search_form_class = SearchForm
    search_fields = ['name__icontains']
    paginate_by = 5
    ordering = ['category', 'name']
    search_fields = ['name__icontains', 'description__icontains']

    def post(self, request, *args, **kwargs):
        for product_pk in request.POST.getlist('products', []):
            print(self.request.POST.getlist('products', []))
            request.session['key'] = 'value'
        return redirect("webapp:product_view")

    def get_queryset(self):
        return self.model.objects.filter(balance__gt=0)

    def get_success_url(self):
        return reverse('webapp:index', kwargs={'pk': self.object.product.pk})


class ProductDetail(DetailView):
    model = Product
    template_name = 'product/product_view.html'

    def get_context_data(self, **kwargs):
        my_dict = self.request.session.get('key', {})
        my_dict['test'] = 1
        self.request.session['key'] = my_dict
        # self.request.session['key']['test'] = 1
        context = super().get_context_data(**kwargs)
        product = self.object
        # order = product.order.order_by('-name')
        # context['order'] = order
        return context


class ProductCreate(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/create.html'
    context_object_name = 'products'
    permission_required = 'webapp.add_product'

    def form_valid(self, form):
        print(self.kwargs.get('pk'))
        form.instance.project = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk })


class ProductUpdate(PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_update.html'
    context_object_name = 'products'
    permission_required = 'webapp.change_product'

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().products.users.all()


    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.products.pk })


class ProductDelete(PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = "product/product_delete.html"
    redirect_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_product'

    def has_permission(self):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        return super().has_permission() and self.request.user in self.get_object().product.users.all()

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_product') or self.get_object().users == self.request.user

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})

source/webapp/templates/partial/form.html
{% if not fields_only %}
{% csrf_token %}
{% endif %}

{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}
{% for field in form %}
    <p><label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label></p>
    <p>{{ field }}</p>
    {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
        {% endfor %}
{% endfor %}
{% if not fields_only %}
    <p><input type="submit" class="btn btn-primary" value="{{ button_text }}"></p>
{% endif %}

source/webapp/templates/partial/form_add_to_cart.html
<form action="{% url 'webapp:add_to_cart' product.pk %}?next={{ request.path }}" method="post" class="d-inline-block">
    {% csrf_token %}
    <div class="input-group mb-3">
        <input type="number" class="form-control" min="1" value="1" name="qty">
        <button type="submit" class="btn btn-success">Добавить в корзину</button>
    </div>
</form>

source/webapp/templates/partial/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-dismissible fade show {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            alert-danger
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            alert-warning
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            alert-success
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            alert-primary
        {% else %}
            alert-secondary
        {% endif %}" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}

source/webapp/templates/partial/pagination.html
<ul class="pagination">
    {% if not page_obj.has_previous %}
        <li class="page-item disabled">
            <a class="page-link">&laquo; В начало</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link">Назад</a>
        </li>
    {% else %}
        <li class="page-item">
            <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page=1">&laquo; В начало</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Назад</a>
        </li>
        <li class="page-item"><a class="page-link"
                                 href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        </li>
    {% endif %}

    <li class="page-item active" aria-current="page">
         <form method="get">
             {% if search %}<input type="hidden" name="search" value="{{ search }}">{% endif %}
            <input type="text" class="form-control" name="page" value="{{ page_obj.number }}">
        </form>
{#        <a class="page-link" href="#">{{ page_obj.number }}</a>#}
    </li>

    {% if not page_obj.has_next %}
        <li class="page-item disabled">
            <a class="page-link">Далее</a>
        </li>

        <li class="page-item disabled">
            <a class="page-link">В конец &raquo;</a>

        </li>
    {% else %}
        <li class="page-item"><a class="page-link"
                                 href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
        <li class="page-item">
            <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Далее</a>

        </li>
        <li class="page-item">
            <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>

        </li>
    {% endif %}
</ul>

source/webapp/templates/partial/product_form.html
{% csrf_token %}

{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}


{% for field in form %}
    <div class="mb-3">
        <p><label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label></p>
        {{ field }}
        {% for error in field.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
{% endfor %}
<button type="submit" class="btn btn-primary">{{ button_text }}</button>

source/webapp/templates/partial/product_list.html
<div class="row">
    {% for product in products %}
        <div class="col-sm-6 my-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'webapp:product_view' product.pk %}">{{ product.name }}</a></h5>
                    <p class="card-text">Цена: {{ product.price }}</p>
                    <p class="card-text">Категория: {{ product.get_category_display }}</p>
                    {% include 'partial/form_add_to_cart.html' %}
                    <a href="{% url 'webapp:product_update' product.pk %}" class="btn btn-primary">Редактировать</a>
                    <a href="{% url 'webapp:product_delete' product.pk %}" class="btn btn-danger">Удалить</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}